# Generated by Django 6.0.7 on 2026-07-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('suggestion', models.TextField(verbose_name='اقتراح عملي')),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تنبيه'), ('critical', 'حرج')], default='warning', max_length=20)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تنبيه أداء',
                'verbose_name_plural': 'تنبيهات الأداء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('completion_rate', models.FloatField(help_text='من 0 إلى 100', verbose_name='نسبة الإنجاز %')),
                ('response_time_hours', models.FloatField(verbose_name='متوسط زمن الاستجابة (ساعة)')),
                ('open_tickets', models.PositiveIntegerField(default=0, verbose_name='الطلبات المفتوحة')),
                ('closed_tickets', models.PositiveIntegerField(default=0, verbose_name='الطلبات المغلقة')),
                ('maturity_score', models.FloatField(help_text='من 0 إلى 5', verbose_name='درجة النضج')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سجل أداء',
                'verbose_name_plural': 'سجلات الأداء',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MaturityFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='العامل')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('impact', models.CharField(choices=[('positive', 'إيجابي'), ('negative', 'سلبي')], max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='أهمية العامل نسبياً', verbose_name='الوزن')),
                ('is_active', models.BooleanField(default=True)),
                ('related_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='analytics.performancerecord', verbose_name='الشهر المرتبط')),
            ],
            options={
                'verbose_name': 'عامل نضج',
                'verbose_name_plural': 'عوامل النضج',
            },
        ),
    ]
