# Generated by Django 6.0.7 on 2026-07-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='المجال')),
                ('pillar', models.CharField(blank=True, max_length=100, verbose_name='الركيزة')),
                ('criteria_count', models.PositiveIntegerField(default=0, verbose_name='عدد المعايير')),
                ('maturity_score', models.FloatField(default=0, help_text='من 0 إلى 5', verbose_name='درجة النضج الحالية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مجال نضيء',
                'verbose_name_plural': 'مجالات نضيء',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='maturity_score',
            field=models.FloatField(help_text='من 0 إلى 5 (6 مستويات)', verbose_name='درجة النضج'),
        ),
    ]
